CREATE TABLE IF NOT EXISTS user(
    user_id VARCHAR(36) PRIMARY KEY,
    user_name VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(35) NOT NULL UNIQUE,
    bio VARCHAR(255),
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE IF NOT EXISTS tag(
    tag_id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS question(
    id VARCHAR(36) PRIMARY KEY,
    text VARCHAR(255) NOT NULL,
    created_at DATETIME,
    updated_at DATETIME,
    user VARCHAR(36) NOT NULL,
    FOREIGN KEY (user) REFERENCES user(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS answer(
    id VARCHAR(36) PRIMARY KEY,
    text MEDIUMTEXT NOT NULL,
    created_at DATETIME,
    updated_at DATETIME,
    user VARCHAR(36) NOT NULL,
    question VARCHAR(36) NOT NULL,
    FOREIGN KEY (user) REFERENCES user(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (question) REFERENCES question(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS question_tag_list(
    question VARCHAR(36) NOT NULL,
    tag VARCHAR(36) NOT NULL,
    FOREIGN KEY (question) REFERENCES question(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (tag) REFERENCES tag(tag_id) ON DELETE CASCADE ON UPDATE CASCADE
);
