CREATE TABLE IF NOT EXISTS comment(
    id VARCHAR(36) PRIMARY KEY,
    created_at DATETIME,
    updated_at DATETIME,
    text TEXT NOT NULL,
    user VARCHAR(36) NOT NULL,
    answer VARCHAR(36) NOT NULL,
    FOREIGN KEY (user) REFERENCES user(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (answer) REFERENCES answer(id) ON DELETE CASCADE ON UPDATE CASCADE
)